name: monikode_event_store
description: "A singleton service to log events into a Firebase Firestore database. Can also log events locally into the console with different log levels (debug, info, warning, error, trace)."
repository: https://github.com/VictorDelamonica/EventStore
homepage: https://www.monikode.com
version: 2.2.0

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true